version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatsheet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # myapp:
  #   build: 
  #     context: . 
  #     dockerfile: Dockerfile
  #   container_name: chatsheet_myapp
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   restart: on-failure

volumes:
  pgdata: